spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_LOCAL_URL}jdbc:mysql://localhost:3306/ssafy_crewup?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    root: INFO
    com.ssafy.crewup: DEBUG
    org.apache.ibatis: DEBUG
    org.springframework.web: DEBUG

app:
  server:
    url: http://localhost:8080