spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_LOCAL_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    root: INFO
    com.ssafy.crewup: DEBUG
    org.apache.ibatis: DEBUG
    org.springframework.web: DEBUG

app:
  server:
    url: http://localhost:8080
  cors:
      allowed-origins: http://localhost:*


