spring:
  application:
    name: crewup-server

  profiles:
    active: local

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME:crewup-images}
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ssafy.crewup.domain
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL